---
- name: ensure haproxy config dir
  file:
    dest: '{{ haproxy_config_dir }}'
    state: directory

- name: create haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: '{{ haproxy_config_dir }}/haproxy.cfg'

- name: test haproxy configuration
  docker_container:
    state: started
    restart: yes
    recreate: yes
    restart_policy: no
    auto_remove: no
    detach: no
    interactive: no
    name: haproxy-configtest
    links: '{{ haproxy_links }}'
    networks: '{{ haproxy_networks }}'
    image: '{{ haproxy_image }}:{{ haproxy_version }}'
    volumes: '{{ haproxy_volumes }}'
    entrypoint: ''
    command: 'haproxy -c -V -f /usr/local/etc/haproxy/haproxy.cfg'

- name: run haproxy container
  docker_container:
    state: started
    restart: no
    recreate: no
    name: '{{ haproxy_container_name }}'
    image: '{{ haproxy_image }}:{{ haproxy_version }}'
    restart_policy: always
    published_ports: '{{ haproxy_published_ports }}'
    links: '{{ haproxy_links }}'
    network_mode: '{{ haproxy_network_mode }}'
    networks: '{{ haproxy_networks }}'
    sysctls: '{{ haproxy_sysctls }}'
    ulimits: '{{ haproxy_ulimits }}'
    volumes: '{{ haproxy_volumes }}'
    command: '{{ haproxy_command }}'
    log_driver: '{{ haproxy_container_log_driver }}'
    log_opt: '{{ haproxy_container_log_opt }}'

- name: reload haproxy
  shell: docker kill --signal=HUP {{ haproxy_container_name }}
