---
- name: ensure haproxy config dir
  file:
    dest: '{{ haproxy_config_dir }}'
    state: directory

- name: create haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: '{{ haproxy_config_dir }}/haproxy.cfg'
  notify:
    - reload haproxy

- name: run haproxy container
  docker_container:
    state: started
    restart: no
    recreate: no
    name: '{{ haproxy_container_name }}'
    image: '{{ haproxy_image }}:{{ haproxy_version }}'
    restart_policy: always
    published_ports: '{{ haproxy_published_ports }}'
    links: '{{ haproxy_links }}'
    network_mode: '{{ haproxy_network_mode }}'
    networks: '{{ haproxy_networks }}'
    sysctls: '{{ haproxy_sysctls }}'
    ulimits: '{{ haproxy_ulimits }}'
    volumes: '{{ haproxy_volumes }}'
    command: '{{ haproxy_command }}'
    log_driver: '{{ haproxy_container_log_driver }}'
    log_opt: '{{ haproxy_container_log_opt }}'

- name: reload haproxy
  shell: docker kill --signal=HUP {{ haproxy_container_name }}
